version: '3.3'

services:
  mstream-server: &mstream-server
    environment:
    - TZ=Europe/Moscow
    image: quay.io/kozhukalov/go-adc:latest
    restart: "no"
    volumes:
    - .:/data
    - .:/root/.go-adc
    network_mode: host
    command: go-adc mstream start
  control-server:
    <<: *mstream-server
    command: go-adc control start
  discover-server:
    <<: *mstream-server
    command: go-adc discover start
